name: Linux Zephyr C builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  target:
    name: Target builds
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: System Packages
        run: |
          sudo apt-get install ninja-build doxygen graphviz cppcheck clang-tidy

      - name: Check environment
        run: |
          cmake --version
          gcc --version
          clang --version
          ninja --version
          doxygen --version
          cppcheck --version
          clang-tidy --version

      - name: Install Zephyr
        run: |
          pip3 install west
          echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
          source ~/.bashrc
          west init zephyrproject
          cd zephyrproject/zephyr
          git checkout v3.0.0
          pip3 install -r scripts/requirements.txt
          chmod +x zephyr-env.sh
          echo 'source ${{github.workspace}}/zephyrproject/zephyr/zephyr-env.sh' >> ~/.bashrc
          source ~/.bashrc
          west zephyr-export
          cd ..
          west update
          printenv
          pip3 --version

      - name: Check Environment
        run: |
          printenv
          pip3 --version
